docs: completed sequenceT section
mailupinc/mailupinc.github.io pull request #2
Opened 2021-05-11 15:17 UTC by davidesamp

2021-05-11 15:52 UTC, riccardoleschiutta requested changes
Very good! 🚀 
Just one note: the TOC is now out-of-sync, if you have doctoc installed, could you please re-generate it (via `cd fp-ts-cheatsheet && doctoc index.md`)?
By doing so it'll be probably easier to consult the cheatsheet using GitHub 😃

2021-05-11 15:59 UTC, davidesamp commented
> Very good! 🚀
> Just one note: the TOC is now out-of-sync, if you have doctoc installed, could you please re-generate it (via `cd fp-ts-cheatsheet && doctoc index.md`)?
> By doing so it'll be probably easier to consult the cheatsheet using GitHub 😃

Simply I forgot the TOC 😃 Now it should be ok, let me know

2021-05-12 08:49 UTC, riccardoleschiutta approved these changes

2021-05-13 07:29 UTC, pinkynrg approved these changes

2021-05-13 10:25 UTC, rosdb approved these changes

2021-05-13 11:05 UTC, merged